#!/bin/sh

hostname=$(/bin/cat /proc/sys/kernel/hostname)
secret=${1?none}
url=${2?none}
ip=${3?none}
host=${4?none}
mac=$(/bin/cat /sys/devices/platform/soc/c080000.edma/net/eth1/address)

/usr/bin/curl --fail \
-m 10 \
-G \
--data-urlencode "digilan-token-action=add" \
--data-urlencode "hostname=$hostname" \
--data-urlencode "digilan-token-secret=$secret" \
--data-urlencode "mac=$mac" \
-o /tmp/add_wordpress \
-w %{http_code} \
--resolve "$host:443:$ip" \
--resolve "$host:80:$ip" \
--retry 3 --retry-delay 5 \
$url 2>/tmp/add_config_err
